const actionTypes = {
  UPDATE_CATEGORY_LOADING: 'UPDATE_CATEGORY_LOADING',
  UPDATE_CATEGORY_SUCCESS: 'UPDATE_CATEGORY_SUCCESS',
  UPDATE_CATEGORY_FAILURE: 'UPDATE_CATEGORY_FAILURE'
};

export default actionTypes;
