const actionTypes = {
  DELETE_ATTENDANT_LOADING: 'DELETE_ATTENDANT_LOADING',
  DELETE_ATTENDANT_SUCCESS: 'DELETE_ATTENDANT_SUCCESS',
  DELETE_ATTENDANT_FAILURE: 'DELETE_ATTENDANT_FAILURE'
};

export default actionTypes;
