const actionTypes = {
  ADD_ATTENDANT_LOADING: 'ADD_ATTENDANT_LOADING',
  ADD_ATTENDANT_SUCCESS: 'ADD_ATTENDANT_SUCCESS',
  ADD_ATTENDANT_FAILURE: 'ADD_ATTENDANT_FAILURE'
};

export default actionTypes;
