const actionTypes = {
  DELETE_CATEGORY_LOADING: 'DELETE_CATEGORY_LOADING',
  DELETE_CATEGORY_SUCCESS: 'DELETE_CATEGORY_SUCCESS',
  DELETE_CATEGORY_FAILURE: 'DELETE_CATEGORY_FAILURE'
};

export default actionTypes;
