const actionTypes = {
  GET_ATTENDANTS_LOADING: 'GET_ATTENDANTS_LOADING',
  GET_ATTENDANTS_SUCCESS: 'GET_ATTENDANTS_SUCCESS',
  GET_ATTENDANTS_FAILURE: 'GET_ATTENDANTS_FAILURE'
};

export default actionTypes;
