const actionTypes = {
  GET_CATEGORIES_LOADING: 'GET_CATEGORIES_LOADING',
  GET_CATEGORIES_SUCCESS: 'GET_CATEGORIES_SUCCESS',
  GET_CATEGORIES_FAILURE: 'GET_CATEGORIES_FAILURE'
};

export default actionTypes;
