const actionTypes = {
  DELETE_PRODUCT_LOADING: 'DELETE_PRODUCT_LOADING',
  DELETE_PRODUCT_SUCCESS: 'DELETE_PRODUCT_SUCCESS',
  DELETE_PRODUCT_FAILURE: 'DELETE_PRODUCT_FAILURE'
};

export default actionTypes;
