const actionTypes = {
  UPDATE_PRODUCT_LOADING: 'UPDATE_PRODUCT_LOADING',
  UPDATE_PRODUCT_SUCCESS: 'UPDATE_PRODUCT_SUCCESS',
  UPDATE_PRODUCT_FAILURE: 'UPDATE_PRODUCT_FAILURE'
};

export default actionTypes;
